spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?user={RDS_USERNAME}&password={RDS_PASSWORD}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    jpa:
      hibernate.ddl-auto: create-drop
      generate-ddl: true
      show-sql: true


cloud:
  aws:
    credentials:
      #      access-key: AKIA2NE3G4UXLMPRFNTC
      #      secret-key: mzX7qXT4OJT5Z0hd3pWDT/k+76ppWu5Rhp/WgijE
      access-key: Youraccesskey
      secret-key: Yoursecretkey
    region:
      static: us-east-2
    stack:
      auto: false
  dynamodb:
    endpoint: dyanmodb.us-east-2.amazonaws.com


#      mysql information
#spring:
#  datasource:
#    url: jdbc:mysql://sip-database.cgkujkrya8vn.us-east-1.rds.amazonaws.com:3306/sip-database
#    username: admin
#    password: admin123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#jpa:
#  hibernate:
#    ddl-auto: update
#  show-sql: true
#  database-platform: org.hibernate.dialect.MySQLDialect

application:
  bucket:
    name: {S3_URL}

server:
  port:5000