cloud:
  aws:
    credentials:
      #      access-key: AKIA2NE3G4UXLMPRFNTC
      #      secret-key: mzX7qXT4OJT5Z0hd3pWDT/k+76ppWu5Rhp/WgijE
      access-key: Youraccesskey
      secret-key: Yoursecretkey
    region:
      static: us-east-2
    stack:
      auto: false

#      mysql information
#spring:
#  datasource:
#    url: jdbc:mysql://sip-database.cgkujkrya8vn.us-east-1.rds.amazonaws.com:3306/sip-database
#    username: admin
#    password: admin123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#jpa:
#  hibernate:
#    ddl-auto: update
#  show-sql: true
#  database-platform: org.hibernate.dialect.MySQLDialect

application:
  bucket:
    name: elasticbeanstalk-us-east-2-298867771596

server:
  port:5000