package com.cs790.app.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.Document;



@Document(collection = "Task")
@Data
@NoArgsConstructor
@AllArgsConstructor
//@DynamoDBTable(tableName = "Task")
public class Task {
//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
    @Id
    private String id;
//    @DynamoDBAttribute
    private String userId;
//    @DynamoDBAttribute
    private String description;
//    @DynamoDBAttribute
    private String dueDate;
//    @DynamoDBAttribute
    private boolean isCompleted;
//    @DynamoDBAttribute
    private String imageUrl;
}
